Ingredient.create(name: 'vers de terre')
Ingredient.create(name: 'dent cassée')
Ingredient.create(name: "crachat d'alcoolique")
Ingredient.create(name: 'citron')
Ingredient.create(name: 'jus de chaussettes')
